#!/bin/sh

#######
##### Generate JCL to run the Unix enumeration tools
##### tooling. 
######

##### 
##  Change the following lines as required to run on your system
####

STDOUT="SYSOUT=*" # <--- ENUM and OMVSEnum output destination
folder='/u/mainframe' # <--- Folder to run tools from
JAVAC='/usr/lpp/java/J8.0_64/bin/javac' # <--- javac path
JAVA='/usr/lpp/java/J8.0_64/bin/java' # <--- Must point to a valid java
C89='/bin/c89' # <--- 31-bit compiler used for the optional SAF helper
MAKE='/bin/make' # <--- make utility
# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# Ensure trailing slash
case "$folder" in
  */) ;;
  *)  folder="$folder/" ;;
esac

cat << EOF
//OMVSENUM JOB (JOB),'JOB',CLASS=A,MSGCLASS=A,
//         NOTIFY=&SYSUID,REGION=0M
//*********************************************************************
//****
//**** GENERATED BY UNIXENUM.SH - DO NOT EDIT
//****
//*********************************************************************
//*********************************************************************
//* Delete the files if they exist
//*********************************************************************
//REMOVE    EXEC PGM=BPXBATCH
//STDIN     DD DUMMY
//STDOUT    DD DUMMY
//STDERR    DD DUMMY     
//STDPARM   DD *
SH cd $folder;
 rm ENUM.rexx;
 rm -f OMVSEnum.java;
 rm -f OMVSEnum.class;
 rm -f OMVSSecurityChecks.java;
 rm -f OMVSSecurityChecks*.class;
 rm -f safauth safauth.c;
 rm -f Makefile;
 rm GhostWalker.java;
 rm portscan.java;
//*********************************************************************
//PUTFILE  PROC FOLDER='$folder',FILENAME=''
//*********************************************************************
//**** Put the files in unix
//*********************************************************************
//PUTFILE  EXEC PGM=IEBGENER
//SYSPRINT DD SYSOUT=*
//SYSUT1   DD DUMMY
//SYSUT2   DD PATH='&FOLDER.&FILENAME',
//            PATHOPTS=(ORDWR,OCREAT), 
//            PATHDISP=(KEEP,DELETE),
//            PATHMODE=(SIRWXU,SIRGRP),            
//            FILEDATA=TEXT               
//SYSIN   DD  DUMMY
// PEND
//*********************************************************************
//PUTENUM EXEC PUTFILE,FILENAME='ENUM.rexx'
//PUTFILE.SYSUT1 DD DATA,DLM='@@'
EOF
cat ../ENUM
cat << 'EOF'
@@
//*********************************************************************
//PUTFSTJ EXEC PUTFILE,FILENAME='GhostWalker.java'
//PUTFILE.SYSUT1 DD DATA,DLM='@@'
EOF
cat GhostWalker.java
cat << 'EOF'
@@
//*********************************************************************
//PUTPOMVS EXEC PUTFILE,FILENAME='OMVSEnum.java'
//PUTFILE.SYSUT1 DD DATA,DLM='@@'
EOF
cat OMVSEnum.java
cat << EOF
@@
//*********************************************************************
//PUTSEC   EXEC PUTFILE,FILENAME='OMVSSecurityChecks.java'
//PUTFILE.SYSUT1 DD DATA,DLM='@@'
EOF
cat OMVSSecurityChecks.java
cat << EOF
@@
//*********************************************************************
//PUTSAF   EXEC PUTFILE,FILENAME='safauth.c'
//PUTFILE.SYSUT1 DD DATA,DLM='@@'
EOF
cat safauth.c
cat << EOF
@@
//*********************************************************************
//PUTPORTS EXEC PUTFILE,FILENAME='portscan.java'
//PUTFILE.SYSUT1 DD DATA,DLM='@@'
EOF
cat portscan.java
cat << EOF
@@
//*********************************************************************
//PUTMAKE  EXEC PUTFILE,FILENAME='Makefile'
//PUTFILE.SYSUT1 DD DATA,DLM='@@'
EOF
cat Makefile
cat << EOF
@@
//*********************************************************************
//* Run ENUM
//*********************************************************************
//ENUMREXX  EXEC PGM=BPXBATCH
//STDIN     DD DUMMY
//STDOUT    DD $STDOUT
//STDERR    DD SYSOUT=*
//STDPARM   DD *
SH cd $folder;
 ./ENUM.rexx SEC;
 ./ENUM.rexx SVC;
 ./ENUM.rexx APF;
 ./ENUM.rexx USSU;
//*********************************************************************
//* Build Java programs and optional native SAF helper
//*********************************************************************
//BUILD     EXEC PGM=BPXBATCH
//STDIN     DD DUMMY
//STDOUT    DD SYSOUT=*
//STDERR    DD SYSOUT=*
//STDPARM   DD *
SH cd $folder;
 if test ! -x $MAKE; then
  echo \"ERROR: make utility unavailable: $MAKE\";
  exit 1;
 fi;
 if test -x $C89; then
  $MAKE JAVAC=$JAVAC CC=$C89 all;
 else
  echo \"WARNING: C89 unavailable; SAF checks skipped\";
  $MAKE JAVAC=$JAVAC java;
 fi;
//*********************************************************************
//* Run OMVSENUM
//*********************************************************************
//OMVSENUM  EXEC PGM=BPXBATCH
//STDIN     DD DUMMY
//STDOUT    DD $STDOUT
//STDERR    DD SYSOUT=*
//STDPARM   DD *
SH set JAVA_HOME=/usr/lpp/java/J8.0_64;
 cd $folder;
 $JAVA -cp . OMVSEnum;
//*********************************************************************
//* Run FileSystemTraversal 
//*********************************************************************
//RUNFSTJ   EXEC PGM=BPXBATCH
//STDIN     DD DUMMY
//STDOUT    DD SYSOUT=*
//STDERR    DD SYSOUT=*     
//STDPARM   DD *
SH set JAVA_HOME=/usr/lpp/java/J8.0_64;
 cd $folder;
 JAVA=$JAVA;
 GW='GhostWalker';
 \$JAVA -cp . \$GW -w /u > u.writable-by-user.txt;
 \$JAVA -cp . \$GW -W /u > u.world-writable.txt;
 \$JAVA -cp . \$GW -w /etc > etc.writable-by-user.txt;
 \$JAVA -cp . \$GW -W /etc > etc.world-writable.txt;
 \$JAVA -cp . \$GW -w /opt > opt.writable-by-user.txt;
 \$JAVA -cp . \$GW -W /opt > opt.world-writable.txt;
 \$JAVA -cp . \$GW -w /usr > usr.writable-by-user.txt;
 \$JAVA -cp . \$GW -W /usr > usr.world-writable.txt;
 \$JAVA -cp . \$GW -w /var > var.writable-by-user.txt;
 \$JAVA -cp . \$GW -W /var > var.world-writable.txt;
//*********************************************************************
EOF
